name: abc_example
description: Abc example.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  build: ^2.3.1
  built_collection: ^5.1.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  equatable: ^2.0.5
  meta: ^1.8.0
  path: ^1.8.2
  source_gen: ^1.2.6
  abc:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  generator_test: ^0.2.0
  source_gen_test: ^1.0.4
