targets:
  $default:
    builders:
      :abc:
        enabled: true

builders:
  abc:
    import: "package:abc/builder.dart"
    builder_factories: ["builder"]
    build_extensions: { ".dart": [".abc.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
